pushing private back to public

diff --git a/modules/landing_zone_vsi/templates/storage_tb_bootdrive_user_data/cloud_init.yml b/modules/landing_zone_vsi/templates/storage_tb_bootdrive_user_data/cloud_init.yml
--- a/modules/landing_zone_vsi/templates/storage_tb_bootdrive_user_data/cloud_init.yml
+++ b/modules/landing_zone_vsi/templates/storage_tb_bootdrive_user_data/cloud_init.yml
@@ -6,38 +6,103 @@ resize_rootfs: false
 write_files:
   - content: |
       #!/usr/bin/env bash
-      # Setup logging
-      exec > >(tee /var/log/ibm_spectrumscale_user-data.log)
-      exec 2>&1
-      set -e
+      if grep -q "Red Hat" /etc/os-release
+      then
+          USER=vpcuser
+          PACKAGE_MGR=dnf
+          if grep -q "platform:el9" /etc/os-release
+          then
+              subscription-manager repos --enable=rhel-9-for-x86_64-supplementary-eus-rpms
+              package_list="python3 kernel-devel-$(uname -r) kernel-headers-$(uname -r) firewalld numactl make gcc-c++ elfutils-libelf-devel bind-utils iptables-nft nfs-utils elfutils elfutils-devel python3-dnf-plugin-versionlock cryptsetup clevis clevis-luks clevis-dracut tpm2-tools"
+          elif grep -q "platform:el8" /etc/os-release
+          then
+              package_list="python38 kernel-devel-$(uname -r) kernel-headers-$(uname -r) firewalld numactl jq make gcc-c++ elfutils-libelf-devel bind-utils iptables nfs-utils elfutils elfutils-devel python3-dnf-plugin-versionlock cryptsetup clevis clevis-luks clevis-dracut tpm2-tools"
+          fi
 
-      # Configure SSH
-      mkdir -p ~/.ssh
-      chmod 700 ~/.ssh
-      echo "${storage_public_key_content}" | base64 --decode >> /root/.ssh/authorized_keys
+          RETRY_LIMIT=5
+          retry_count=0
+          all_pkg_installed=1
+
+          while [[ $all_pkg_installed -ne 0 && $retry_count -lt $RETRY_LIMIT ]]
+          do
+              # Install all required packages
+              echo "INFO: Attempting to install packages"
+              $PACKAGE_MGR install -y --allowerasing $package_list
+
+              # Check to ensure packages are installed
+              pkg_installed=0
+              for pkg in $package_list
+              do
+                  pkg_query=$($PACKAGE_MGR list installed $pkg)
+                  pkg_installed=$(($? + $pkg_installed))
+              done
+              if [[ $pkg_installed -ne 0 ]]
+              then
+                  # The minimum required packages have not been installed.
+                  echo "WARN: Required packages not installed. Sleeping for 60 seconds and retrying..."
+                  touch /var/log/scale-rerun-package-install
+                  echo "INFO: Cleaning and repopulating repository data"
+                  $PACKAGE_MGR clean all
+                  $PACKAGE_MGR makecache
+                  sleep 60
+              else
+                  all_pkg_installed=0
+              fi
+              retry_count=$(( $retry_count+1 ))
+          done
+
+          yum update --security -y
+          yum versionlock add $package_list
+          yum versionlock list
+          echo 'export PATH=$PATH:/usr/lpp/mmfs/bin' >> /root/.bashrc
+      elif grep -q "Ubuntu" /etc/os-release
+      then
+          USER=ubuntu
+      fi
+
+      sed -i -e "s/^/no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command=\"echo \'Please login as the user \\\\\"$USER\\\\\" rather than the user \\\\\"root\\\\\".\';echo;sleep 10; exit 142\" /" ~/.ssh/authorized_keys
+      echo "${storage_private_key_content}" | base64 --decode > /root/.ssh/id_rsa
+      chmod 600 ~/.ssh/id_rsa
       echo "${bastion_public_key_content}" | base64 --decode >> /root/.ssh/authorized_keys
+      echo "${storage_public_key_content}" | base64 --decode >> /root/.ssh/authorized_keys
       echo "StrictHostKeyChecking no" >> ~/.ssh/config
-      echo "${storage_private_key_content}" | base64 --decode >> ~/.ssh/id_rsa
-      chmod 600 ~/.ssh/id_rsa ~/.ssh/authorized_keys
+      echo "DOMAIN=\"${storage_dns_domain}\"" >> "/etc/sysconfig/network-scripts/ifcfg-eth0"
+      echo "MTU=9000" >> "/etc/sysconfig/network-scripts/ifcfg-eth0"
+      sed -i -e "s#QUEUE_COUNT=3#QUEUE_COUNT=\`ethtool -l \$iface | echo \$(awk '\$1 ~ /Combined:/ {print \$2;exit}')\`#g" /var/lib/cloud/scripts/per-boot/iface-config
       ethtool -L eth0 combined 16
+      chage -I -1 -m 0 -M 99999 -E -1 -W 14 vpcuser
+      systemctl restart NetworkManager
+      systemctl stop firewalld
+      firewall-offline-cmd --zone=public --add-port=1191/tcp
+      firewall-offline-cmd --zone=public --add-port=4444/tcp
+      firewall-offline-cmd --zone=public --add-port=4444/udp
+      firewall-offline-cmd --zone=public --add-port=4739/udp
+      firewall-offline-cmd --zone=public --add-port=4739/tcp
+      firewall-offline-cmd --zone=public --add-port=9084/tcp
+      firewall-offline-cmd --zone=public --add-port=9085/tcp
+      firewall-offline-cmd --zone=public --add-service=http
+      firewall-offline-cmd --zone=public --add-service=https
+      firewall-offline-cmd --zone=public --add-port=2049/tcp
+      firewall-offline-cmd --zone=public --add-port=2049/udp
+      firewall-offline-cmd --zone=public --add-port=111/tcp
+      firewall-offline-cmd --zone=public --add-port=111/udp
+      firewall-offline-cmd --zone=public --add-port=30000-61000/tcp
+      firewall-offline-cmd --zone=public --add-port=30000-61000/udp
+      systemctl start firewalld
+      systemctl enable firewalld
 
-      # Banner configuration
-      echo "###########################################################################################" >> /etc/motd
-      echo "# You have logged in to Storage BareMetal Server.                                         #" >> /etc/motd
-      echo "#                                                                                         #" >> /etc/motd
-      echo "# Refer: https://cloud.ibm.com/docs/vpc?topic=vpc-bare-metal-servers-storage              #" >> /etc/motd
-      echo "###########################################################################################" >> /etc/motd
-      USER=vpcuser
-      PACKAGE_MGR=dnf
-      package_list="python38 kernel-devel-$(uname -r) kernel-headers-$(uname -r) firewalld numactl jq make gcc-c++ elfutils-libelf-devel bind-utils iptables nfs-utils elfutils elfutils-devel python3-dnf-plugin-versionlock cryptsetup clevis clevis-luks clevis-dracut tpm2-tools"
-      $PACKAGE_MGR install -y $package_list
-      yum update --security -y
-      yum versionlock add $package_list
-      yum versionlock list
-      echo 'export PATH=$PATH:/usr/lpp/mmfs/bin' >> /root/.bashrc
-      # Create completion marker
-      touch /var/user_data_complete
-      echo "User data script completed successfully at $(date)"
+      if [ "${enable_protocol}" == true ]; then
+          sec_interface=$(nmcli -t con show --active | grep eth1 | cut -d ':' -f 1)
+          nmcli conn del "$sec_interface"
+          nmcli con add type ethernet con-name eth1 ifname eth1
+          echo "DOMAIN=\"${protocol_dns_domain}\"" >> "/etc/sysconfig/network-scripts/ifcfg-eth1"
+          echo "MTU=9000" >> "/etc/sysconfig/network-scripts/ifcfg-eth1"
+          systemctl restart NetworkManager
+          ###### TODO: Fix Me ######
+          echo 'export IC_REGION=${vpc_region}' >> /root/.bashrc
+          echo 'export IC_SUBNET=${protocol_subnet_id}' >> /root/.bashrc
+          echo 'export IC_RG=${resource_group_id}' >> /root/.bashrc
+      fi
     path: /usr/local/bin/scale_user_data.sh
     permissions: '0755'
   - content: |
@@ -102,11 +167,11 @@ write_files:
       # it ensures that the 'cp' alias isn't used.)
       efidir=$(ls /boot/efi/EFI/ | grep -v BOOT)
       \cp -f /boot/grub2/grubenv /boot/efi/EFI/$${efidir}/
-      # We MUST have a separate /boot partition to host the kernel and initramfs unencrypted
+      # We MUST have a separate /boot partiiton to host the kernel and initramfs unencrypted
       # as these are needed to unlock the root drive.  The IBM CLoud RHEL 9.x images have
-      # a separate boot partition, but 8.x do not.
+      # a separate boot partiiton, but 8.x do not.
       # If we dont have a separate /boot partition, we'll use the current root partition
-      # as /boot.  So copy the current /boot content into the root of the filesystem.
+      # as /boot.  So copy the current /boot content into the root of the filessytem.
       if ! lsblk -l | grep /boot$; then
           rsync -a --exclude='/efi*' /boot/ /
           # Current root device UUID - it will become boot device uuid
